### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by Sil3ntStorm** [btzy/nativefiledialog-extended#81] opened 2022-11-24 10:34 UTC
When using this on Linux and calling OpenDialog the application instantly terminates

```
Gtk:ERROR:../../../../gtk/gtkpathbar.c:1754:gtk_path_bar_get_info_callback: assertion failed: (cancellable == file_info->path_bar->priv->get_info_cancellable)
Bail out! Gtk:ERROR:../../../../gtk/gtkpathbar.c:1754:gtk_path_bar_get_info_callback: assertion failed: (cancellable == file_info->path_bar->priv->get_info_cancellable)
```

when not using gtk but dbus instead there is simply a segmentation fault.

**Comment by btzy** [comment] 2022-11-24 16:25
Please share your OS version, and ideally a GitHub Actions link or build script.  Also, try out the samples - if the samples work but your code doesn't work, then you probably aren't calling NFD correctly.

**Comment by btzy** [comment] 2022-12-04 17:10
Closing this because there is not enough information to reproduce.  Feel free to reopen it when you can provide clear instructions that will allow me to reproduce the crash.

**Closed by btzy** 2022-12-04 17:10 UTC
